name: SonarQube Scan

on:
  push:
    branches:
      - main
      - oj 

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm run test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      with:
        args: >
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.test.inclusions=tests/**/*.test.js,tests/**/*.test.jsx
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.exclusions=node_modules/**,coverage/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
